# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: explorer-indexer
networks:
- id: 10
  start_block: 0
  contracts:
  - name: Datadisks
    address:
    - 0x5ce61b80931Ea67565f0532965DDe5be2d41331d
    - 0x92B55D5254bC93A4f282224A9C3bD2b7e0eF37fc
    handler: src/EventHandlers.ts
    events:
    - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
  - name: Handbooks
    address:
    - 0x235f3dfe5106f137d8b137c1b7fa115076e8b476
    - 0xdeDEBfC6893D5e7e87Db8A1a88667D2BB746C231
    - 0x58da595fec45ca61cc68883869885e378caf0231
    - 0x0ae1cfd5f84bde987b255e822463a17705ad9ba9
    - 0xa22ed08b4ed3a34ce5c1802748ed8b294f3ec926
    - 0xb9Eef5b84D862e45e6C425574BE23b11CA9211f3
    - 0xe2dd5eb9841920937833c094874ba33d26becb4f
    - 0x8C21eABd632B41f840690C56D9dda70C9FD6E55e
    - 0xd94ecc2f45d7346975f2437c789b3e2e32c397ca
    handler: src/EventHandlers.ts
    events:
    - event: Transfer(address indexed _from, address indexed _to, uint256 _value)
- id: 137
  start_block: 0
  contracts:
  - name: PolBadges
    address:
    - 0x3436d8af0b617DeEF5AADBaFC56f293e102DD886
    handler: src/EventHandlers.ts
    events:
    - event: TransferSingle(address indexed operator, address indexed from, address indexed to, uint256 id, uint256 value)
rollback_on_reorg: false
